// LOGIN
export const LOG_IN = "LOG_IN";
export const LOG_IN_FAIL = "LOG_IN_FAIL";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";

// ---------------- SERVICES --------------- //

// SERVICE_LIST
export const SERVICE_LIST = "SERVICE_LIST";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";

// SERVICE_NEW
export const SERVICE_NEW = "SERVICE_NEW";
export const SERVICE_NEW_FAIL = "SERVICE_NEW_FAIL";
export const SERVICE_NEW_SUCCESS = "SERVICE_NEW_SUCCESS";

// SERVICE_UPDATE
export const SERVICE_UPDATE = "SERVICE_UPDATE";
export const SERVICE_UPDATE_FAIL = "SERVICE_UPDATE_FAIL";
export const SERVICE_UPDATE_SUCCESS = "SERVICE_UPDATE_SUCCESS";

// SERVICE_REMOVE
export const SERVICE_REMOVE = "SERVICE_REMOVE";
export const SERVICE_REMOVE_FAIL = "SERVICE_REMOVE_FAIL";
export const SERVICE_REMOVE_SUCCESS = "SERVICE_REMOVE_SUCCESS";

// ---------------- USERS --------------- //

// USERS_LIST
export const USERS_LIST = "USERS_LIST";
export const USERS_LIST_FAIL = "USERS_LIST_FAIL";
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS";

// KYC_LIST
export const KYC_LIST = "KYC_LIST";
export const KYC_LIST_FAIL = "KYC_LIST_FAIL";
export const KYC_LIST_SUCCESS = "KYC_LIST_SUCCESS";

// WITHDRAW_LIST
export const WITHDRAW_LIST = "WITHDRAW_LIST";
export const WITHDRAW_LIST_FAIL = "WITHDRAW_LIST_FAIL";
export const WITHDRAW_LIST_SUCCESS = "WITHDRAW_LIST_SUCCESS";

// MANAGE_KYC
export const MANAGE_KYC = "MANAGE_KYC";
export const MANAGE_KYC_FAIL = "MANAGE_KYC_FAIL";
export const MANAGE_KYC_SUCCESS = "MANAGE_KYC_SUCCESS";

// MANAGE_WITHDRAW
export const MANAGE_WITHDRAW = "MANAGE_WITHDRAW";
export const MANAGE_WITHDRAW_FAIL = "MANAGE_WITHDRAW_FAIL";
export const MANAGE_WITHDRAW_SUCCESS = "MANAGE_WITHDRAW_SUCCESS";
